#!/bin/bash

echo am33xx_pwm > /sys/devices/bone_capemgr.9/slots
echo bone_pwm_P9_14 > /sys/devices/bone_capemgr.9/slots
echo bone_pwm_P8_13 > /sys/devices/bone_capemgr.9/slots

echo 0 > /sys/devices/ocp.2/pwm_test_P9_14.14/polarity
echo 20000000 > /sys/devices/ocp.2/pwm_test_P9_14.14/period
echo 1000000 > /sys/devices/ocp.2/pwm_test_P9_14.14/duty

echo 0 > /sys/devices/ocp.2/pwm_test_P8_13.15/polarity
echo 20000000 > /sys/devices/ocp.2/pwm_test_P8_13.15/period
echo 1000000 > /sys/devices/ocp.2/pwm_test_P8_13.15/duty



